### ISSUE TITLE
species velocity indices

### ISSUE THREAD

**Issue by julien-roux** [pachterlab/kallisto-transcriptome-indices#2]
Hi Lior et al.
Thanks for the good work with Kallisto and Bustools!
Do you have any plan to build and release the "velocity" indices on this page as well?

At least it would be nice to share how the unspliced transcript sequences were obtained. It is not clear in the tutorial https://www.kallistobus.tools/velocity_tutorial.html (`introns.correct_header.fa.gz` file)

Best,
Julien

**Comment by sbooeshaghi** [comment]
Hello! One can make the velocity indices using the command line following this tutorial

https://www.kallistobus.tools/velocity_index_tutorial.html

If you find any mistakes please let me know. Otherwise the tutorial should be straight forward.

**Comment by julien-roux** [comment]
Thanks Sina for putting this online, it's quite useful!

In the meantime I came up with a R/Bioconductor solution for the first steps, that is maybe a bit simpler (although it's probably possible to be even more efficient):

```
library(AnnotationHub)
ah <- AnnotationHub()
query(ah, c("Ensembl", "97", "Homo"))
edb <- ah[["AH73881"]]

# switch to UCSC chromosomes names (used in BSGenome)
seqlevelsStyle(edb) <- "UCSC"
options(ensembldb.seqnameNotFound="ORIGINAL")
library(BSgenome.Hsapiens.UCSC.hg38)
## fetch the coordinates of the exons by transcripts (on validChroms)
validChroms <- intersect(seqlevels(edb), seqlevels(BSgenome.Hsapiens.UCSC.hg38))
exons.gr <- exonsBy(edb, by = "tx", filter=AnnotationFilterList( SeqNameFilter(validChroms) ))
## For compatibility with BSgenome
genome(exons.gr) <- "hg38"
isCircular(exons.gr)["chrM"] <- TRUE

## get transcript sequences (a bit long)
transcripts.seqs <- getSeq(BSgenome.Hsapiens.UCSC.hg38, exons.gr)

## Export to fasta (one record per transcript)
library(Biostrings)
writeXStringSet(unstrsplit(transcripts.seqs), "ensembldb_Homo_sapiens_GRCh38_ensembl_97_transcripts.fasta.gz", compress="gzip")

## Save the transcripts to genes correspondance
transcripts.gr <- unlist(transcriptsBy(edb, by = "gene", filter=AnnotationFilterList( SeqNameFilter(validChroms) )))
write.table(cbind(transcripts.gr$tx_id, transcripts.gr$gene_id), file="tx2gene.tsv", quote=F, sep="\t", col.names = F, row.names = F)

## Get a fasta file of transcripts + extended intronic regions ##############################

## Get exon coordinates by gene, and resize them (extend introns L-1 bp on each side)
read_length <- 58 # In my case
exonExt <- 2 * (read_length - 1)
exonsExt.gr <- exonsBy(edb, by="gene", filter=AnnotationFilterList( SeqNameFilter(validChroms) ))
exonsExt.gr <- reduce(exonsExt.gr)
genome(exonsExt.gr) <- "hg38"
isCircular(exonsExt.gr)["chrM"] <- TRUE
newWidths <- width(exonsExt.gr) - exonExt
newWidths <- lapply(newWidths, function(x){ x[x < 0] <- 0; x}) ## Some exons are shorter than 2 * L-1 bp
exonsExt.gr <- resize(exonsExt.gr, width=newWidths, fix="center")

## For each gene, extract the gaps, and intesect with the gene border coordinates (range)
introns.gr <- setdiff(range(exonsExt.gr), exonsExt.gr)
## Remove genes without introns
introns.gr <- introns.gr[!elementNROWS(introns.gr) == '0']
## Extract sequences
introns.seqs <- getSeq(BSgenome.Hsapiens.UCSC.hg38, introns.gr)
introns.seqs <- unlist(introns.seqs)
names(introns.seqs) <- make.unique(names(introns.seqs))
## Optional: I find it more elegant to have always a number appended to the introns names. Here I add a 0 to the first one
names(introns.seqs)[!grepl("\\.", names(introns.seqs))] <- paste0(names(introns.seqs)[!grepl("\\.", names(introns.seqs))], ".0")
## Append "-I" to the IDs, to get a format similar to the Kallisto tutorials
names(introns.seqs) <- paste0(names(introns.seqs), "-I") 
## Write to file
writeXStringSet(c(unstrsplit(transcripts.seqs), introns.seqs), "ensembldb_Homo_sapiens_GRCh38_ensembl_97_transcripts+introns.fasta.gz", compress="gzip")

## Save the transcripts+introns to genes correspondance
write.table(rbind(cbind(transcripts.gr$tx_id, transcripts.gr$gene_id), cbind(names(introns.seqs), gsub("(ENSG\\d+)\\.\\d+\\-I", "\\1", names(introns.seqs)))), file="tx+introns2gene.tsv", quote=F, sep="\t", col.names = F, row.names = F)
```

BTW, did you study if/how the inclusion of intronic sequences in the index affects the estimates of transcripts abudances?

**Comment by lambdamoses** [comment]
@julien-roux Thank you for your contribution. I also had an implementation with R and Bioconductor but find yours more robust, so I ended up adapting yours in the `BUSpaRse` package. Also note that getting Ensembl version 97 annotation as `EnsDb` from `AnnotationHub` requires Bioconductor 3.9 or 3.10. Bioconductor 3.8 supplies version 94.

**Comment by sbooeshaghi** [comment]
Hey @julien-roux that was a great suggestion. We went ahead and looked at key metrics comparing the kallisto count matrix (made with cDNA index) and the kallisto spliced count matrix (made by the [velocity workflow](https://www.kallistobus.tools/velocity_index_tutorial.html)). We used the same FASTQs used to generate Supplementary Figure 9 & 10, and filtered by the cells that [La Manno et al. 2018](https://doi.org/10.1038/s41586-018-0414-6) used in their [notebook](https://github.com/velocyto-team/velocyto-notebooks/blob/master/python/hgForebrainGlutamatergic.ipynb) . Here are the results: 

![kallisto_vs_kallisto_spliced](https://user-images.githubusercontent.com/10369156/61754766-5faf3500-ad69-11e9-8aee-fed1a747f9f8.png)

In a similar form to the supplementary figures in the [preprint](https://www.biorxiv.org/content/10.1101/673285v1.supplementary-material) each figure is described below:


**A.** “Knee plots” for kallisto and kallisto velocity (spliced) showing, for a given UMI count (x-axis), the number of cells that contain at least that many UMI counts (y-axis). 
**B.** Correspondence in the number of distinct UMIs per cell between the workflows. 
**C.** Genes detected by kallisto and kallisto velocity (spliced) as a function of distinct UMI counts per cell. 
**D.** Pearson correlation between gene counts as a function of the distinct UMI counts per cell. 
**E.** The  distance between gene abundances for each kallisto cell and its corresponding kallisto velocity (spliced) cell (blue) and the  distance between the gene abundances for each kallisto cell and the closest kallisto cell (orange). 
**F.1.** kallisto t-SNE from the first 10 principal components. 
**F.2.** kallisto velocity (spliced) t-SNE from the first 10 principal components. 
**G.** MA plot. Each dot is a gene and the y-axis represents the log2 fold change between the average count for that gene across all cells between kallisto and kallisto velocity (spliced) and the x-axis is the average count for that gene between kallisto and kallisto velocity (spliced).
**H.** Significant differential gene sets between kallisto and kallisto velocity (spliced).

With these results in hand we believe that the spliced matrix made from the velocity workflow **is concordant** with the standard count matrix made with the standard kallisto workflow, and since the process for making the spliced count matrix is symmetric with that for making the unspliced count matrix, we believe the unspliced count matrices are also concordant with those that would be made with the standard kallisto workflow and an intron index.
